apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: invoked-template-example-
  namespace: argo
spec:
  entrypoint: workflow-runner

  templates:
  - name: workflow-runner
    dag:
      tasks:
      - name: workflow-1
        arguments:
          parameters:
          - name: tap_image
            value: tap-exchange-rates
        templateRef:
          name: singer-tap-to-csv-template
          template: tap-to-target

      - name: workflow-2
        arguments:
          parameters:
          - name: tap_image
            value: tap-exchange-rates
        templateRef:
          name: singer-tap-to-csv-template
          template: tap-to-target

      - name: workflow-3
        arguments:
          parameters:
          - name: tap_image
            value: tap-exchange-rates
        templateRef:
          name: singer-tap-to-csv-template
          template: tap-to-target

          