apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: singer-tap-covid-19-
  namespace: argo
spec:
  entrypoint: tap-to-target

  templates:
  - name: tap-to-target
    inputs:
      parameters:
      - name: tap_image
        value: tap-covid-19
      - name: target_image
        value: target-csv
      - name: github_api_token
        value: 3cd19e1bac7d9696ce83a81f93ed500fd7c44d6f
    steps:
    - - name: tap
        template: singer-tap
        arguments:
          parameters:
          - name: tap_image
            value: "{{inputs.parameters.tap_image}}"
          - name: github_api_token
            value: "{{inputs.parameters.github_api_token}}"
    - - name: target
        template: singer-target
        arguments:
          parameters:
          - name: target_image
            value: "{{inputs.parameters.target_image}}"
          - name: tap_image
            value: "{{inputs.parameters.tap_image}}"
          artifacts:
          - name: tap-output
            from: "{{steps.tap.outputs.artifacts.tap-output}}"

  - name: singer-tap
    container:
      image: "stkbailey/{{inputs.parameters.tap_image}}:latest"
    inputs:
      parameters:
      - name: tap_image
      - name: github_api_token
      artifacts:
      - name: tap-config
        path: /tmp/config.json
        raw:
          data: |
            {
              "api_token": "{{inputs.parameters.github_api_token}}",
              "start_date": "2020-09-01T00:00:00Z",
              "user_agent": "tap-covid-19 tutorial@immuta.com"
            }
    outputs:
      artifacts:
      - name: tap-output
        path: /tmp/tap_output.txt

  - name: singer-target
    container:
      image: "stkbailey/{{inputs.parameters.target_image}}:latest"
    inputs:
      parameters:
      - name: target_image
      - name: tap_image
      artifacts:
      - name: target-config
        path: /tmp/config.json
        raw:
          data: |
            {"delimiter": "\t", "quotechar": "'", "destination_path": "/tmp/data/"}
      - name: tap-output
        path: /tmp/tap_input.txt
    outputs:
      artifacts:
      - name: target-output
        path: /tmp/target_output.txt
      - name: target-data
        path: /tmp/data/data.zip
        s3:
          bucket: singer
          key: "outputs/{{inputs.parameters.tap_image}}/results.zip"
          endpoint: argo-artifacts:9000
          insecure: true
          accessKeySecret:
            name: argo-artifacts
            key: accesskey
          secretKeySecret:
            name: argo-artifacts
            key: secretkey
